### PR TITLE
Add horizontal/vertical window split commands

### PR DESCRIPTION
**Pull request by ehamberg**

### CODE REVIEW

**Comment by andrewdhazlett** [comment]
these are already mapped under `<leader>w-` and `<leader>w/`

**Comment by ehamberg** [comment]
Right. I'm just used to using `<SPC>wv` and `<SPC>ws` in spacemacs – probably beucase I've always used `<C-w>v` and `<C-w>s` in Vim. (`<C-w>/` and `<C-w>-` doesn't work in Vim.)

These are documented in section 12.5.3.1 in the [spacemacs documentation](http://spacemacs.org/doc/DOCUMENTATION.html).

**Comment by jb55** [comment]
:+1:

**Comment by jimmay5469** [comment]
Looks good, thanks!

**Pull request merged**
